# Generated by Django 4.2.8 on 2023-12-07 01:34

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CargoType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Faction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_recruiting", models.BooleanField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name="FactionTrait",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Ship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified", models.DateTimeField(auto_now=True)),
                ("symbol", models.CharField(max_length=32, unique=True)),
                ("registration", models.JSONField(default=dict)),
                ("crew", models.JSONField(default=dict)),
                ("frame", models.JSONField(default=dict)),
                ("reactor", models.JSONField(default=dict)),
                ("engine", models.JSONField(default=dict)),
                ("cooldown", models.JSONField(default=dict)),
                ("cargo_capacity", models.PositiveIntegerField(default=0)),
                ("cargo_units", models.PositiveIntegerField(default=0)),
                ("fuel", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="ShipModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True, null=True)),
                ("capacity", models.PositiveIntegerField(default=0)),
                ("range", models.PositiveIntegerField(default=0)),
                ("requirements", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="ShipMount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True, null=True)),
                ("strength", models.PositiveIntegerField(default=0)),
                (
                    "deposits",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=32),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("requirements", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="System",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=32, unique=True)),
                ("sector", models.CharField(max_length=32)),
                ("type", models.CharField(db_index=True, max_length=32)),
                ("x", models.IntegerField(editable=False)),
                ("y", models.IntegerField(editable=False)),
                ("factions", models.ManyToManyField(to="galaxy.faction")),
            ],
        ),
        migrations.CreateModel(
            name="WaypointModifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="WaypointTrait",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Waypoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified", models.DateTimeField(auto_now=True)),
                ("symbol", models.CharField(max_length=32, unique=True)),
                ("type", models.CharField(db_index=True, max_length=32)),
                ("x", models.IntegerField(editable=False)),
                ("y", models.IntegerField(editable=False)),
                ("is_under_construction", models.BooleanField(default=False)),
                (
                    "faction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="galaxy.faction",
                    ),
                ),
                ("modifiers", models.ManyToManyField(to="galaxy.waypointmodifier")),
                (
                    "orbits",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orbitals",
                        to="galaxy.waypoint",
                    ),
                ),
                (
                    "system",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="waypoints",
                        to="galaxy.system",
                    ),
                ),
                ("traits", models.ManyToManyField(to="galaxy.waypointtrait")),
            ],
        ),
        migrations.CreateModel(
            name="ShipNav",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified", models.DateTimeField(auto_now=True)),
                ("route", models.JSONField(default=dict)),
                ("status", models.CharField(max_length=32)),
                ("flight_mode", models.CharField(max_length=32)),
                (
                    "system",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="galaxy.system",
                    ),
                ),
                (
                    "waypoint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="galaxy.waypoint",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShipCargoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("units", models.PositiveIntegerField(default=0)),
                (
                    "ship",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="galaxy.ship",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="galaxy.cargotype",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ship",
            name="modules",
            field=models.ManyToManyField(to="galaxy.shipmodule"),
        ),
        migrations.AddField(
            model_name="ship",
            name="mounts",
            field=models.ManyToManyField(to="galaxy.shipmount"),
        ),
        migrations.AddField(
            model_name="ship",
            name="nav",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="galaxy.shipnav"
            ),
        ),
        migrations.AddField(
            model_name="faction",
            name="headquarters",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="galaxy.system",
            ),
        ),
        migrations.AddField(
            model_name="faction",
            name="traits",
            field=models.ManyToManyField(to="galaxy.factiontrait"),
        ),
        migrations.CreateModel(
            name="Chart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submitted_by", models.CharField(max_length=32)),
                ("submitted_on", models.DateTimeField(editable=False)),
                (
                    "waypoint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="galaxy.waypoint",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified", models.DateTimeField(auto_now=True)),
                ("account_id", models.CharField(max_length=64, unique=True)),
                ("symbol", models.CharField(max_length=32)),
                ("email", models.EmailField(blank=True, max_length=256, null=True)),
                ("credits", models.IntegerField(default=0)),
                ("ship_count", models.IntegerField(default=0)),
                (
                    "headquarters",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="galaxy.waypoint",
                    ),
                ),
                (
                    "starting_faction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="galaxy.faction",
                    ),
                ),
            ],
        ),
    ]
