# Generated by Django 4.2.8 on 2023-12-28 03:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galaxy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ship",
            name="behaviour",
            field=models.CharField(
                blank=True,
                choices=[
                    (None, "None"),
                    ("TRADE", "Trading"),
                    ("MINE", "Mining"),
                    ("HAUL", "Hauling"),
                ],
                help_text="Desired autonomous behaviour",
                max_length=32,
                null=True,
            ),
        ),
    ]
