# Generated by Django 4.2.8 on 2023-12-20 23:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galaxy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradegood",
            name="inputs",
            field=models.ManyToManyField(blank=True, to="galaxy.tradegood"),
        ),
        migrations.AlterField(
            model_name="faction",
            name="traits",
            field=models.ManyToManyField(blank=True, to="galaxy.factiontrait"),
        ),
        migrations.AlterField(
            model_name="market",
            name="exchange",
            field=models.ManyToManyField(
                blank=True, related_name="exchange", to="galaxy.tradegood"
            ),
        ),
        migrations.AlterField(
            model_name="market",
            name="exports",
            field=models.ManyToManyField(
                blank=True, related_name="exports", to="galaxy.tradegood"
            ),
        ),
        migrations.AlterField(
            model_name="market",
            name="imports",
            field=models.ManyToManyField(
                blank=True, related_name="imports", to="galaxy.tradegood"
            ),
        ),
        migrations.AlterField(
            model_name="markettradegood",
            name="trade_matches",
            field=models.ManyToManyField(blank=True, to="galaxy.markettradegood"),
        ),
        migrations.AlterField(
            model_name="ship",
            name="modules",
            field=models.ManyToManyField(blank=True, to="galaxy.shipmodule"),
        ),
        migrations.AlterField(
            model_name="ship",
            name="mounts",
            field=models.ManyToManyField(blank=True, to="galaxy.shipmount"),
        ),
        migrations.AlterField(
            model_name="shipyardship",
            name="modules",
            field=models.ManyToManyField(blank=True, to="galaxy.shipmodule"),
        ),
        migrations.AlterField(
            model_name="shipyardship",
            name="mounts",
            field=models.ManyToManyField(blank=True, to="galaxy.shipmount"),
        ),
        migrations.AlterField(
            model_name="system",
            name="factions",
            field=models.ManyToManyField(blank=True, to="galaxy.faction"),
        ),
        migrations.AlterField(
            model_name="waypoint",
            name="modifiers",
            field=models.ManyToManyField(blank=True, to="galaxy.waypointmodifier"),
        ),
        migrations.AlterField(
            model_name="waypoint",
            name="traits",
            field=models.ManyToManyField(blank=True, to="galaxy.waypointtrait"),
        ),
    ]
