# Generated by Django 4.2.8 on 2024-01-03 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("galaxy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="type",
            field=models.CharField(
                choices=[
                    ("PROCUREMENT", "procurement"),
                    ("TRANSPORT", "transport"),
                    ("SHUTTLE", "shuttle"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="markettradegood",
            name="activity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("WEAK", "weak"),
                    ("GROWING", "growing"),
                    ("STRONG", "strong"),
                    ("RESTRICTED", "restricted"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="markettradegood",
            name="supply",
            field=models.CharField(
                choices=[
                    ("SCARCE", "scarce"),
                    ("LIMITED", "limited"),
                    ("MODERATE", "moderate"),
                    ("HIGH", "high"),
                    ("ABUNDANT", "abundant"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="markettradegood",
            name="type",
            field=models.CharField(
                choices=[
                    ("EXPORT", "export"),
                    ("IMPORT", "import"),
                    ("EXCHANGE", "exchange"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="ship",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ships",
                to="galaxy.agent",
            ),
        ),
        migrations.AlterField(
            model_name="shipnav",
            name="flight_mode",
            field=models.CharField(
                choices=[
                    ("DRIFT", "drift"),
                    ("STEALTH", "stealth"),
                    ("CRUISE", "cruise"),
                    ("BURN", "burn"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="shipnav",
            name="status",
            field=models.CharField(
                choices=[
                    ("IN_TRANSIT", "in transit"),
                    ("IN_ORBIT", "in orbit"),
                    ("DOCKED", "docked"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="shipnav",
            name="system",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shipnavs",
                to="galaxy.system",
            ),
        ),
        migrations.AlterField(
            model_name="shipnav",
            name="waypoint",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shipnavs",
                to="galaxy.waypoint",
            ),
        ),
        migrations.AlterField(
            model_name="shipyardship",
            name="type",
            field=models.CharField(
                choices=[
                    ("SHIP_PROBE", "probe"),
                    ("SHIP_MINING_DRONE", "mining drone"),
                    ("SHIP_SIPHON_DRONE", "siphon drone"),
                    ("SHIP_INTERCEPTOR", "interceptor"),
                    ("SHIP_LIGHT_HAULER", "light hauler"),
                    ("SHIP_COMMAND_FRIGATE", "command frigate"),
                    ("SHIP_EXPLORER", "explorer"),
                    ("SHIP_HEAVY_FREIGHTER", "heavy freighter"),
                    ("SHIP_LIGHT_SHUTTLE", "light shuttle"),
                    ("SHIP_ORE_HOUND", "ore hound"),
                    ("SHIP_REFINING_FREIGHTER", "refining freighter"),
                    ("SHIP_SURVEYOR", "surveyor"),
                ],
                db_index=True,
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="system",
            name="type",
            field=models.CharField(
                choices=[
                    ("NEUTRON_STAR", "neutron star"),
                    ("RED_STAR", "red star"),
                    ("ORANGE_STAR", "orange star"),
                    ("BLUE_STAR", "blue star"),
                    ("YOUNG_STAR", "young star"),
                    ("WHITE_DWARF", "white dwarf"),
                    ("BLACK_HOLE", "black hole"),
                    ("HYPERGIANT", "hypergiant"),
                    ("NEBULA", "nebula"),
                    ("UNSTABLE", "unstable"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[("PURCHASE", "purchase"), ("SELL", "sell")], max_length=32
            ),
        ),
        migrations.AlterField(
            model_name="waypoint",
            name="type",
            field=models.CharField(
                choices=[
                    ("PLANET", "planet"),
                    ("GAS_GIANT", "gas giant"),
                    ("MOON", "moon"),
                    ("ORBITAL_STATION", "orbital station"),
                    ("JUMP_GATE", "jump gate"),
                    ("ASTEROID_FIELD", "asteroid field"),
                    ("ASTEROID", "asteroid"),
                    ("ENGINEERED_ASTEROID", "engineered asteroid"),
                    ("ASTEROID_BASE", "asteroid base"),
                    ("NEBULA", "nebula"),
                    ("DEBRIS_FIELD", "debris field"),
                    ("GRAVITY_WELL", "gravity well"),
                    ("ARTIFICIAL_GRAVITY_WELL", "artificial gravity well"),
                    ("FUEL_STATION", "fuel station"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
    ]
