# Generated by Django 4.2.8 on 2023-12-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galaxy", "0002_tradegood_inputs_alter_faction_traits_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shipyardtransaction",
            name="agent",
        ),
        migrations.AddField(
            model_name="shipyardtransaction",
            name="agent_symbol",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
